// Main Interactions

// Module-level blog data — populated async from posts/manifest.json
let blogData = [];

document.addEventListener('DOMContentLoaded', async () => {
    // Mobile Navigation Toggle
    const nav = document.querySelector('nav');
    const headerContainer = document.querySelector('header .container');

    // Create Hamburger Button dynamically
    const menuBtn = document.createElement('button');
    menuBtn.className = 'mobile-menu-btn';
    menuBtn.innerHTML = '☰'; // Simple hamburger icon
    menuBtn.setAttribute('aria-label', 'Toggle navigation');

    // Insert before nav
    headerContainer.insertBefore(menuBtn, nav);

    menuBtn.addEventListener('click', () => {
        nav.classList.toggle('active');
        menuBtn.innerHTML = nav.classList.contains('active') ? '✕' : '☰';
    });

    // Close menu when clicking a link
    nav.querySelectorAll('a').forEach(link => {
        link.addEventListener('click', () => {
            if (nav.classList.contains('active')) {
                nav.classList.remove('active');
                menuBtn.innerHTML = '☰';
            }
        });
    });

    // Fetch blog post metadata from manifest (generated by scripts/build-blog.js)
    blogData = await fetchBlogData();

    // Render Projects
    renderProjects();

    // Render Blog Posts (for lists like index or blog.html)
    const blogContainer = document.getElementById('blog-container');
    if (blogContainer) {
        const limit = blogContainer.getAttribute('data-limit');
        // Category tabs only exist on blog.html (not on the homepage preview)
        renderCategoryTabs();
        renderBlogPosts(limit ? parseInt(limit, 10) : undefined);
    }

    // Render Single Post (only if on post.html)
    renderSinglePost();
});

// Fetch posts/manifest.json — source of truth for which posts exist
async function fetchBlogData() {
    try {
        const res = await fetch('posts/manifest.json');
        if (!res.ok) return [];
        return await res.json();
    } catch {
        return [];
    }
}

// Render dynamic projects from projectsData array
function renderProjects() {
    const container = document.getElementById('projects-container');
    const template = document.getElementById('project-card-template');

    // Make sure we have the container, template, and data before proceeding
    if (!container || !template || typeof projectsData === 'undefined') return;

    projectsData.forEach(project => {
        const clone = template.content.cloneNode(true);

        const titleEl = clone.querySelector('.project-title');
        if (titleEl) titleEl.textContent = project.title;

        const descEl = clone.querySelector('.project-description');
        if (descEl) descEl.textContent = project.description;

        const previewEl = clone.querySelector('.project-preview');
        if (previewEl) previewEl.textContent = project.previewText;

        const linkEl = clone.querySelector('.project-link');
        if (linkEl) linkEl.href = project.link;

        container.appendChild(clone);
    });
}

// Render category filter tabs on blog.html
// Tabs are auto-generated from the unique categories present in blogData —
// no HTML changes needed when adding new categories.
function renderCategoryTabs() {
    const container = document.getElementById('category-tabs-container');
    if (!container) return;

    // Collect unique categories in insertion order (preserves manifest ordering)
    const seen = new Set();
    const categories = ['All'];
    blogData.forEach(p => {
        if (!seen.has(p.category)) {
            seen.add(p.category);
            categories.push(p.category);
        }
    });

    categories.forEach(cat => {
        const btn = document.createElement('button');
        btn.textContent = cat;
        btn.className = 'category-tab';
        btn.dataset.category = cat;
        if (cat === 'All') btn.classList.add('active');

        btn.addEventListener('click', () => {
            container.querySelectorAll('.category-tab').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            renderBlogPosts(undefined, cat === 'All' ? null : cat);
        });

        container.appendChild(btn);
    });
}

// Render dynamic blog posts from blogData array.
// limit: optional number of posts to render (renders all if omitted)
// categoryFilter: optional category string to filter by (renders all if null/undefined)
function renderBlogPosts(limit, categoryFilter) {
    const container = document.getElementById('blog-container');
    const template = document.getElementById('blog-post-template');

    if (!container || !template) return;

    // Clear any previously rendered posts before re-rendering
    container.innerHTML = '';

    let postsToRender = limit ? blogData.slice(0, limit) : [...blogData];

    if (categoryFilter) {
        postsToRender = postsToRender.filter(p => p.category === categoryFilter);
    }

    // Graceful empty state — shown when a category has no posts yet
    if (postsToRender.length === 0) {
        const empty = document.createElement('div');
        empty.style.cssText = 'background: var(--bg-glass); backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px); padding: 3rem 2rem; border-radius: 12px; border: 1px solid var(--border-color); text-align: center;';
        
        const title = document.createElement('h3');
        title.style.cssText = 'font-size: 1.5rem; margin-bottom: 0.5rem; color: var(--text-primary);';
        title.textContent = 'Nothing here yet';
        
        const subtitle = document.createElement('p');
        subtitle.style.cssText = 'color: var(--text-secondary); margin-bottom: 0;';
        subtitle.textContent = 'Check back soon for new thoughts and explorations.';
        
        empty.appendChild(title);
        empty.appendChild(subtitle);
        container.appendChild(empty);
        return;
    }

    postsToRender.forEach(post => {
        const clone = template.content.cloneNode(true);

        const categoryEl = clone.querySelector('.blog-category');
        if (categoryEl) categoryEl.textContent = post.category;

        const dateEl = clone.querySelector('.blog-date');
        if (dateEl) dateEl.textContent = post.date || '';

        const titleEl = clone.querySelector('.blog-title');
        if (titleEl) titleEl.textContent = post.title;

        const descEl = clone.querySelector('.blog-description');
        if (descEl) descEl.textContent = post.description;

        const linkEl = clone.querySelector('.blog-link');
        if (linkEl) linkEl.href = `post.html?id=${post.id}`;

        container.appendChild(clone);
    });
}

// Logic for rendering a single post on post.html
async function renderSinglePost() {
    const singlePostContainer = document.getElementById('single-post-container');
    const errorContainer = document.getElementById('post-error');

    // Check if we are actually on the post page
    if (!singlePostContainer || !errorContainer) return;

    // Get ID from URL
    const urlParams = new URLSearchParams(window.location.search);
    const postId = urlParams.get('id');

    // Find the matching post object
    const post = blogData.find(p => p.id === postId);

    if (post) {
        // Set document title
        document.title = `${post.title} | Jorge Soto`;

        // Populate the DOM metadata
        document.getElementById('post-category').textContent = post.category;
        document.getElementById('post-date').textContent = post.date;
        document.getElementById('post-title').textContent = post.title;

        // Fetch the corresponding markdown file and render it
        try {
            const response = await fetch(`posts/${post.id}.md`);
            if (!response.ok) throw new Error('Post content not found');

            const raw = await response.text();

            // Strip YAML frontmatter (--- ... ---) before rendering
            const markdownText = raw.replace(/^---[\s\S]*?---\r?\n?/, '');

            // Parse Markdown to HTML if marked is loaded, otherwise drop in raw text
            const htmlContent = typeof marked !== 'undefined' ? marked.parse(markdownText) : markdownText;

            document.getElementById('post-content').innerHTML = htmlContent;
        } catch (error) {
            console.error(error);
            document.getElementById('post-content').innerHTML = "<p><em>Sorry, we couldn't load the content for this post.</em></p>";
        }

    } else {
        // Handle post not found
        singlePostContainer.style.display = 'none';
        errorContainer.style.display = 'block';
    }
}
